version: 0.0
os: linux
files:
  - source: ./VijayJavaHelloWorld.war
    destination: /tmp/
hooks:
  ApplicationStop:
    - location: stop_server.sh
    - location: undeploy_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_application.sh
    - location: start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: validate_tomcat_is_running.sh
    - location: validate_application_is_running.sh
